webtalk_init -webtalk_dir C:\\Xilinx_Project_Vivado\\GPIO_Useage\\GPIO_Useage.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "星期三 十月 1 18:00:06 2014" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210923700_0_0_904" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "i6jv3ic5gqfh656k3vsao4sb0v" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.2_35" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "35" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2295 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1412156667143" -context "sdk\\\\hardware/1412156667143"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1412156667143"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1412156667143"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.2" -context "sdk\\\\hardware/1412156667143"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1412156667143"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1412156667143"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1412156667143"
webtalk_add_data -client sdk -key uid -value "1412157416419" -context "sdk\\\\bsp/1412157416419"
webtalk_add_data -client sdk -key hwid -value "1412156667143" -context "sdk\\\\bsp/1412157416419"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1412157416419"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1412157416419"
webtalk_add_data -client sdk -key uid -value "1412157419394" -context "sdk\\\\application/1412157419394"
webtalk_add_data -client sdk -key hwid -value "1412156667143" -context "sdk\\\\application/1412157419394"
webtalk_add_data -client sdk -key bspid -value "1412157416419" -context "sdk\\\\application/1412157419394"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1412157419394"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1412157419394"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1412157419394"
webtalk_transmit -clientid 87301643 -regid "210923700_0_0_904" -xml C:\\Xilinx_Project_Vivado\\GPIO_Useage\\GPIO_Useage.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Xilinx_Project_Vivado\\GPIO_Useage\\GPIO_Useage.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Xilinx_Project_Vivado\\GPIO_Useage\\GPIO_Useage.sdk\\webtalk\\sdk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
